fix(sdk): Prefer KID and Algorithm selection from key maps (#2475)
When key mappings (grants now with key ids!) are available,
prefer those values when possible, even if that means having multiple
mechanism types in the same TDF (e.g. RSA keys of different lengths).
This was always the intent, but apparently didn't work before.

I've added a couple of small tests,
and now will add more to the integration tests.

Also, updates `start-up-with-containers` to automatically drop
unsupported key types on older kases.
This will simplify xtest loading the newly supported key types.

### Proposed Changes

* the `kao template` type is now the preferred input format for
`prepareManifest`
* move migration code (from `splitPlan`) into separate method
* modifies tests to correctly associate keys with key ids


### Checklist

- [ ] I have added or updated unit tests
- [ ] I have added or updated integration tests (if appropriate)
- [ ] I have added or updated documentation

### Testing Instructions

---------

Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>

diff --git a/test/start-up-with-containers/action.yaml b/test/start-up-with-containers/action.yaml
--- a/test/start-up-with-containers/action.yaml
+++ b/test/start-up-with-containers/action.yaml
@@ -12,10 +12,9 @@ inputs:
     description: A JSON array containing extra keys for the KAS to load. Each object should have 'kid', 'alg', 'private', and 'cert' fields.
     default: '[]'
   ec-tdf-enabled:
-    default: false
+    default: "false"
     description: 'Whether to enable ECC wrapping for TDFs'
     required: false
-    type: boolean
 
 outputs:
   platform-working-dir:
@@ -48,6 +47,21 @@ runs:
           otdf-test-platform/service/go.sum
           otdf-test-platform/protocol/go/go.sum
           otdf-test-platform/sdk/go.sum
+    - name: Lookup current platform version
+      shell: bash
+      id: platform-version
+      run: |-
+        if ! go run ./service version; then
+          # NOTE: the version command was added in 0.4.37
+          echo "Error: Unable to get platform version; defaulting to tag 0.3.0"
+          echo "PLATFORM_VERSION=0.3.0" >> "$GITHUB_ENV"
+          exit
+        fi
+        # Older version commands output version to stderr; newer versions output to stdout
+        PLATFORM_VERSION=$(go run ./service version 2>&1)
+        echo "PLATFORM_VERSION=$PLATFORM_VERSION" >> "$GITHUB_ENV"
+        echo "## Platform version output: [$PLATFORM_VERSION]"
+      working-directory: otdf-test-platform
     - name: Provide the platform with keys
       shell: bash
       run: .github/scripts/init-temp-keys.sh
@@ -58,11 +72,20 @@ runs:
         EXTRA_KEYS: ${{ inputs.extra-keys }}
       run: |
         set -e
-
+        allowed_algorithms=(ec:secp256r1 rsa:2048)
+        if echo $PLATFORM_VERSION | awk -F. '{ if ($1 > 0 || ($1 == 0 && $2 > 7) || ($1 == 0 && $2 == 7 && $3 >= 1)) exit 0; else exit 1; }'; then
+          # For versions 0.7.1 and later, we allow rsa:4096 ec:secp384r1 ec:secp521r1 
+          allowed_algorithms+=(rsa:4096 ec:secp384r1 ec:secp521r1)
+        fi
         keyring='[{"kid":"ec1","alg":"ec:secp256r1"},{"kid":"r1","alg":"rsa:2048"}]'
-        keys='[{"kid":"ec1","alg":"ec:secp256r1","private":"kas-ec-private.pem","cert":"kas-ec-cert.pem"},{"kid":"r1","alg":"rsa:2048","private":"kas-private.pem","cert":"kas-cert.pem"}]'
+        keys='[{"kid":"e1","alg":"ec:secp256r1","private":"kas-ec-private.pem","cert":"kas-ec-cert.pem"},{"kid":"ec1","alg":"ec:secp256r1","private":"kas-ec-private.pem","cert":"kas-ec-cert.pem"},{"kid":"r1","alg":"rsa:2048","private":"kas-private.pem","cert":"kas-cert.pem"}]'
         while IFS= read -r -d $'\0' key_json <&3; do
           printf 'processing %s\n' "${key_json}"
+          alg="$(jq -r '.alg' <<< "${key_json}")"
+          if [[ ! " ${allowed_algorithms[*]} " =~ " ${alg} " ]]; then
+            printf 'algorithm [%s] is not allowed. Skipping extra key [%s]\n' "${alg}" "${kid}" 1>&2
+            continue
+          fi
           private_pem="$(jq -r '.privateKey' <<< "${key_json}")"
           cert_pem="$(jq -r '.cert' <<< "${key_json}")"
           kid="$(jq -r '.kid' <<< "${key_json}")"
