chore(ci): remove duplicate env and update name (#349)
* Update checks.yaml

* Update .github/workflows/checks.yaml

Co-authored-by: Dave Mihalcik <dmihalcik@virtru.com>

* Apply suggestions from code review

* Update checks.yaml

* Update .github/workflows/checks.yaml

---------

Co-authored-by: Dave Mihalcik <dmihalcik@virtru.com>

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -78,8 +78,8 @@ jobs:
           mkdir -p $(pwd)/.tmp/tokens
           echo "directories.tokendir = $(pwd)/.tmp/tokens" > softhsm2.conf
           echo "log.level = DEBUG" >> softhsm2.conf
-          export SOFTHSM2_CONF=$(pwd)/softhsm2.conf
-      - run: SOFTHSM2_CONF="$(pwd)/softhsm2.conf" go test ./... -short
+          echo "SOFTHSM2_CONF=$(pwd)/softhsm2.conf" >> "$GITHUB_ENV"
+      - run: go test ./... -short
         working-directory: ${{ matrix.directory }}
 
   integration:
@@ -163,8 +163,8 @@ jobs:
       - name: Set up JDK
         uses: actions/setup-java@v3
         with:
-          java-version: '20'
-          distribution: 'adopt'
+          java-version: "20"
+          distribution: "adopt"
           server-id: github
       - name: Compile Java SDK
         run: |
@@ -180,7 +180,7 @@ jobs:
     if: always()
     steps:
       - if: contains(needs.*.result, 'failure')
-        run: exit 1
+        run: echo "Failed due to ${{ contains(needs.*.result, 'failure') }}" && exit 1
 
   license:
     name: license check
